#!/usr/bin/env python3
"""
Local LLM Demo

This example demonstrates how to run the Agent Runtime with local LLM models
using Ollama or other local providers via LiteLLM.

Prerequisites:
1. Install Ollama: https://ollama.ai
2. Pull a model: ollama pull llama2 (or mistral, codellama, etc.)
3. Start Ollama server (usually runs automatically)

Usage:
    python examples/local_llm_demo.py
    python examples/local_llm_demo.py --model ollama/mistral
    python examples/local_llm_demo.py --mock  # Use mock provider for testing
"""

import argparse
import asyncio
import sys
from datetime import datetime

# Add src to path for development
sys.path.insert(0, "src")

from aegis.llm import (
    LLMClient,
    LLMClientConfig,
    LiteLLMProvider,
    MockProvider,
    Conversation,
)
from aegis.tools import ToolRegistry, ToolDefinition
from aegis.audit import AuditLogger, InMemoryAuditStorage
from aegis.gcl import CommitmentManager, RuntimeCommitment


def create_local_provider(model: str, ollama_host: str = "http://localhost:11434"):
    """Create a LiteLLM provider configured for local models."""
    return LiteLLMProvider(
        api_base=ollama_host,
        custom_llm_provider="ollama",
    )


def create_mock_provider():
    """Create a mock provider for testing without a real LLM."""
    return MockProvider(
        default_response="This is a mock response. In a real deployment, "
        "this would be generated by a local LLM like Llama 2 or Mistral."
    )


async def setup_tools(client: LLMClient) -> None:
    """Register demo tools with the client."""
    
    async def get_current_time() -> str:
        """Get the current date and time."""
        now = datetime.now()
        return f"Current time: {now.strftime('%Y-%m-%d %H:%M:%S')}"
    
    async def calculate(expression: str) -> str:
        """Evaluate a mathematical expression."""
        try:
            # Safe evaluation for simple math
            allowed_names = {"abs": abs, "round": round, "min": min, "max": max}
            result = eval(expression, {"__builtins__": {}}, allowed_names)
            return f"Result: {result}"
        except Exception as e:
            return f"Error: {str(e)}"
    
    async def echo(message: str) -> str:
        """Echo back a message."""
        return f"Echo: {message}"
    
    # Register tools
    client.register_tool(
        name="get_current_time",
        handler=get_current_time,
        description="Get the current date and time",
        parameters={
            "type": "object",
            "properties": {},
        },
    )
    
    client.register_tool(
        name="calculate",
        handler=calculate,
        description="Evaluate a mathematical expression",
        parameters={
            "type": "object",
            "properties": {
                "expression": {
                    "type": "string",
                    "description": "Mathematical expression to evaluate",
                },
            },
            "required": ["expression"],
        },
    )
    
    client.register_tool(
        name="echo",
        handler=echo,
        description="Echo back a message",
        parameters={
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "description": "Message to echo",
                },
            },
            "required": ["message"],
        },
    )


async def run_demo(
    model: str = "ollama/llama2",
    use_mock: bool = False,
    ollama_host: str = "http://localhost:11434",
) -> None:
    """Run the local LLM demo."""
    
    print("=" * 60)
    print("Agent Runtime - Local LLM Demo")
    print("=" * 60)
    
    # Create provider
    if use_mock:
        print("\nUsing MOCK provider (no real LLM calls)")
        provider = create_mock_provider()
    else:
        print(f"\nUsing LOCAL provider")
        print(f"  Model: {model}")
        print(f"  Ollama Host: {ollama_host}")
        provider = create_local_provider(model, ollama_host)
    
    # Create client
    config = LLMClientConfig(
        default_model=model,
        default_max_tokens=1024,
        default_temperature=0.7,
    )
    client = LLMClient(provider=provider, config=config)
    
    # Setup tools
    await setup_tools(client)
    print(f"\nRegistered {len(client.tool_executor._tools)} tools")
    
    # Setup audit logging
    audit_store = InMemoryAuditStorage()
    audit_logger = AuditLogger(store=audit_store)
    
    # Setup commitment tracking
    commitment_manager = CommitmentManager()
    
    # Create a commitment for the demo
    commitment = RuntimeCommitment(
        debtor="agent",
        creditor="user",
        antecedent="user_request",
        consequent="provide_response",
    )
    commitment_manager.add_commitment(commitment)
    
    print("\n" + "-" * 60)
    print("Interactive Session")
    print("-" * 60)
    print("Type your messages below. Commands:")
    print("  /quit or /exit - End the session")
    print("  /stats - Show session statistics")
    print("  /clear - Clear conversation history")
    print("-" * 60 + "\n")
    
    # Create conversation
    conversation = Conversation(
        system_prompt="You are a helpful assistant running on a local LLM. "
        "You have access to tools for getting the current time, "
        "performing calculations, and echoing messages."
    )
    
    session_id = f"demo-{datetime.now().strftime('%Y%m%d%H%M%S')}"
    
    while True:
        try:
            # Get user input
            user_input = input("You: ").strip()
            
            if not user_input:
                continue
            
            # Handle commands
            if user_input.lower() in ("/quit", "/exit"):
                print("\nEnding session...")
                break
            
            if user_input.lower() == "/stats":
                print(f"\n--- Session Statistics ---")
                print(f"Session ID: {session_id}")
                print(f"Messages: {len(conversation.messages)}")
                print(f"LLM Requests: {client.total_requests}")
                print(f"Total Tokens: {client.total_tokens.total_tokens}")
                
                events = await audit_store.query(session_id=session_id)
                print(f"Audit Events: {len(events)}")
                
                stats = commitment_manager.get_stats()
                print(f"Commitments: {stats.total} total, {stats.fulfilled} fulfilled")
                print("-" * 30 + "\n")
                continue
            
            if user_input.lower() == "/clear":
                conversation.clear()
                print("Conversation cleared.\n")
                continue
            
            # Log user input
            await audit_logger.log_event(
                event_type="user.input",
                agent_id="local-demo",
                session_id=session_id,
                data={"content": user_input},
            )
            
            # Activate commitment
            commitment_manager.activate_commitment(commitment.commitment_id)
            
            # Get response
            print("Agent: ", end="", flush=True)
            
            try:
                response = await client.chat(
                    conversation=conversation,
                    user_message=user_input,
                    model=model,
                )
                
                print(response.get_text())
                
                # Log response
                await audit_logger.log_event(
                    event_type="agent.response",
                    agent_id="local-demo",
                    session_id=session_id,
                    data={
                        "content": response.get_text(),
                        "tokens": response.usage.total_tokens,
                    },
                )
                
                # Fulfill commitment
                commitment_manager.fulfill_commitment(commitment.commitment_id)
                
                # Create new commitment for next interaction
                commitment = RuntimeCommitment(
                    debtor="agent",
                    creditor="user",
                    antecedent="user_request",
                    consequent="provide_response",
                )
                commitment_manager.add_commitment(commitment)
                
            except Exception as e:
                print(f"Error: {str(e)}")
                print("(Make sure Ollama is running and the model is available)")
            
            print()
            
        except KeyboardInterrupt:
            print("\n\nInterrupted. Ending session...")
            break
        except EOFError:
            break
    
    # Final statistics
    print("\n" + "=" * 60)
    print("Session Summary")
    print("=" * 60)
    print(f"Session ID: {session_id}")
    print(f"Total Messages: {len(conversation.messages)}")
    print(f"LLM Requests: {client.total_requests}")
    print(f"Total Tokens: {client.total_tokens.total_tokens}")
    
    events = await audit_store.query(session_id=session_id)
    print(f"Audit Events: {len(events)}")
    
    stats = commitment_manager.get_stats()
    print(f"Commitments: {stats.total} total, {stats.fulfilled} fulfilled")
    print("=" * 60)


def main():
    parser = argparse.ArgumentParser(
        description="Run Agent Runtime with local LLM models"
    )
    parser.add_argument(
        "--model",
        default="ollama/llama2",
        help="Model to use (default: ollama/llama2)",
    )
    parser.add_argument(
        "--ollama-host",
        default="http://localhost:11434",
        help="Ollama server URL (default: http://localhost:11434)",
    )
    parser.add_argument(
        "--mock",
        action="store_true",
        help="Use mock provider instead of real LLM",
    )
    
    args = parser.parse_args()
    
    asyncio.run(run_demo(
        model=args.model,
        use_mock=args.mock,
        ollama_host=args.ollama_host,
    ))


if __name__ == "__main__":
    main()
